import HtmlToCsv from "@/components/csv-tools/html-to-csv";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "HTML Table to CSV Converter - Scrape Tables from HTML to CSV",
  description:
    "Extract data from HTML tables and convert to CSV format. Scrape tables from web pages or pasted HTML. Free online HTML to CSV converter.",
  openGraph: {
    title: "HTML Table to CSV Converter - Scrape Tables from HTML to CSV",
    description:
      "Extract CSV data from HTML tables on web pages or pasted HTML.",
    type: "website",
  },
  alternates: {
    canonical: "https://1000freetools.com/csv-tools/html-to-csv",
  },
};

export default function Page() {
  return (
    <>
      <div className="mx-auto max-w-6xl">
        

        <HtmlToCsv />

        <div className="prose max-w-4xl mx-auto mt-16">
          <h2 className="text-2xl font-semibold mb-4">
            What This Converter Does
          </h2>
          <p className="text-muted-foreground mb-6">
            This tool extracts data from HTML tables and converts it to CSV format. It uses the browser's DOMParser to parse HTML, finds table elements, and extracts rows and cells into structured CSV data. Works with tables from web pages, HTML files, or pasted HTML code.
          </p>

          <h2 className="text-2xl font-semibold mb-4">
            Supported HTML Table Structures
          </h2>
          <p className="text-muted-foreground mb-4">
            <strong>Standard tables:</strong>
          </p>
          <pre className="bg-muted p-4 rounded-lg overflow-x-auto text-sm mb-4">
{`<table>
  <tr><th>Name</th><th>Age</th></tr>
  <tr><td>Alice</td><td>30</td></tr>
  <tr><td>Bob</td><td>25</td></tr>
</table>`}
          </pre>
          <p className="text-muted-foreground mb-4">
            <strong>Tables with thead/tbody:</strong>
          </p>
          <pre className="bg-muted p-4 rounded-lg overflow-x-auto text-sm mb-4">
{`<table>
  <thead><tr><th>Name</th><th>Age</th></tr></thead>
  <tbody>
    <tr><td>Alice</td><td>30</td></tr>
    <tr><td>Bob</td><td>25</td></tr>
  </tbody>
</table>`}
          </pre>
          <p className="text-muted-foreground mb-6">
            Both structures extract correctly. Headers from th elements become the CSV header row.
          </p>

          <h2 className="text-2xl font-semibold mb-4">
            Conversion Options
          </h2>
          <p className="text-muted-foreground mb-4">
            <strong>Delimiter selection:</strong> Choose comma, semicolon, pipe, or tab as the output CSV delimiter.
          </p>
          <p className="text-muted-foreground mb-6">
            <strong>First table extraction:</strong> If HTML contains multiple tables, the first table is extracted by default.
          </p>

          <h2 className="text-2xl font-semibold mb-4">
            When to Use This
          </h2>
          <p className="text-muted-foreground mb-4">
            <strong>Web scraping:</strong> Extract data tables from government statistics, financial reports, or sports data pages.
          </p>
          <p className="text-muted-foreground mb-4">
            <strong>Email data extraction:</strong> Pull tables from HTML email newsletters or reports into analyzable CSV format.
          </p>
          <p className="text-muted-foreground mb-4">
            <strong>Wiki data extraction:</strong> Wikipedia and other wikis use HTML tables for data. Convert to CSV for analysis.
          </p>
          <p className="text-muted-foreground mb-4">
            <strong>Report conversion:</strong> Extract tables from HTML reports generated by business intelligence tools.
          </p>
          <p className="text-muted-foreground mb-6">
            <strong>Archive purposes:</strong> Convert HTML tables to CSV for long-term storage in a format that outlasts specific web pages.
          </p>

          <h2 className="text-2xl font-semibold mb-4">
            How to Use
          </h2>
          <p className="text-muted-foreground mb-4">
            <strong>From web pages:</strong> Right-click the table, select "Inspect" or "View Source", copy the HTML, paste into the tool.
          </p>
          <p className="text-muted-foreground mb-4">
            <strong>From HTML files:</strong> Open the file in a text editor, copy the table HTML, paste into the tool.
          </p>
          <p className="text-muted-foreground mb-4">
            <strong>From rendered pages:</strong> Some browsers let you copy table HTML directly. Right-click the table and look for "Copy element" or similar.
          </p>
          <p className="text-muted-foreground mb-6">
            The tool parses the HTML and extracts all rows with their cell values into CSV format.
          </p>

          <h2 className="text-2xl font-semibold mb-4">
            Handling Complex Tables
          </h2>
          <p className="text-muted-foreground mb-4">
            <strong>Colspan:</strong> Cells spanning multiple columns extract as a single value. Adjacent cells may shift.
          </p>
          <p className="text-muted-foreground mb-4">
            <strong>Rowspan:</strong> Cells spanning multiple rows extract once. Subsequent rows may have empty cells where the spanned cell continues.
          </p>
          <p className="text-muted-foreground mb-4">
            <strong>Nested tables:</strong> Only the outermost table structure extracts. Nested tables within cells become text content.
          </p>
          <p className="text-muted-foreground mb-6">
            <strong>Hidden rows/columns:</strong> CSS display:none or visibility:hidden doesn't affect extraction. All table rows are extracted.
          </p>

          <h2 className="text-2xl font-semibold mb-4">
            What Gets Extracted
          </h2>
          <p className="text-muted-foreground mb-4">
            <strong>Text content:</strong> Only visible text within cells extracts. HTML tags within cells are stripped.
          </p>
          <p className="text-muted-foreground mb-4">
            <strong>Headers:</strong> th elements (from thead or first row) become CSV headers.
          </p>
          <p className="text-muted-foreground mb-6">
            <strong>Links and images:</strong> URLs and alt text don't extract by default. Only the visible text content appears in CSV.
          </p>

          <h2 className="text-2xl font-semibold mb-4">
            Limitations
          </h2>
          <p className="text-muted-foreground mb-4">
            <strong>JavaScript-rendered tables:</strong> Tables generated by JavaScript after page load won't be in the static HTML. You need to copy the rendered HTML from browser DevTools.
          </p>
          <p className="text-muted-foreground mb-4">
            <strong>Complex layouts:</strong> Tables using div-based layouts instead of proper table elements won't be detected.
          </p>
          <p className="text-muted-foreground mb-6">
            <strong>Large HTML:</strong> Very large HTML documents may cause slow parsing. Extract just the table HTML for best performance.
          </p>

          <h2 className="text-2xl font-semibold mb-4">
            Frequently Asked Questions
          </h2>

          <h3 className="text-xl font-semibold mb-2">Can this extract tables from any website?</h3>
          <p className="text-muted-foreground mb-4">
            It extracts from HTML you paste. For live websites, copy the table HTML using browser DevTools. Some sites may have terms of service restricting scraping.
          </p>

          <h3 className="text-xl font-semibold mb-2">Does this handle tables without header rows?</h3>
          <p className="text-muted-foreground mb-4">
            Yes. If no th elements exist, the first row becomes the header. You can edit the CSV afterward if needed.
          </p>

          <h3 className="text-xl font-semibold mb-2">Can I extract multiple tables at once?</h3>
          <p className="text-muted-foreground mb-4">
            This tool extracts the first table from the HTML. For multiple tables, extract each separately or use a script to process them.
          </p>

          <h3 className="text-xl font-semibold mb-2">Can I convert CSV back to HTML?</h3>
          <p className="text-muted-foreground mb-6">
            Yes, use the CSV to HTML Table tool. You can add CSS classes, striped rows, borders, and responsive layout options.
          </p>
        </div>
      </div>
    </>
  );
}
